---
abstract: 'Store session data in the client cookie'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Catalyst: '5.90030'
  Catalyst::Plugin::Session::State::Cookie: '0.17'
  Test::Most: '0.34'
  Test::WWW::Mechanize::Catalyst: '0.60'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.031, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-Plugin-Session-Store-Cookie
requires:
  Catalyst::Plugin::Session: '0.40'
  MRO::Compat: '0.12'
  Moose: '2.1403'
  Session::Storage::Secure: '0.010'
resources:
  bugtracker: https://github.com/jjn1056/Catalyst-Plugin-Session-Store-Cookie/issues
  homepage: https://github.com/jjn1056/Catalyst-Plugin-Session-Store-Cookie
  repository: https://github.com/jjn1056/Catalyst-Plugin-Session-Store-Cookie
version: '0.001'
